# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-11 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='teachCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.CourseInfo')),
            ],
            options={
                'db_table': 'teacherCourse',
            },
        ),
        migrations.CreateModel(
            name='TeacherInfo',
            fields=[
                ('tNum', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tName', models.CharField(max_length=30)),
                ('tSex', models.BooleanField()),
                ('tPassword', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
        migrations.AddField(
            model_name='teachcourse',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.TeacherInfo'),
        ),
        migrations.AlterUniqueTogether(
            name='teachcourse',
            unique_together=set([('teacher', 'course')]),
        ),
    ]
