# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-11 13:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cNum', models.CharField(max_length=15)),
                ('cNo', models.CharField(max_length=4)),
                ('cName', models.CharField(max_length=30)),
                ('cMajor', models.CharField(max_length=50)),
                ('cClassWeek', models.CharField(max_length=25)),
                ('cClassDay', models.IntegerField()),
                ('cClassSessions', models.IntegerField()),
                ('cContinuingSession', models.IntegerField()),
                ('cBegTime', models.TimeField(blank=True)),
                ('cEndTime', models.TimeField(blank=True)),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='FaceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.TextField(max_length=1050)),
            ],
            options={
                'db_table': 'faceInfo',
            },
        ),
        migrations.CreateModel(
            name='SignInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sSignTime', models.DateTimeField(auto_now=True, null=True)),
                ('sIsSign', models.BooleanField(default=False)),
                ('sSignDay', models.IntegerField(default=1)),
                ('sSignWeek', models.IntegerField(default=10)),
                ('sSignBegTime', models.TimeField(default=datetime.time(8, 30))),
                ('sSignEndTime', models.TimeField(default=datetime.time(14, 30))),
                ('sCouse', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='student.CourseInfo')),
            ],
            options={
                'db_table': 'signInfo',
            },
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.CourseInfo')),
            ],
            options={
                'db_table': 'studentcourse',
            },
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('sNum', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('sName', models.CharField(max_length=30)),
                ('sSex', models.BooleanField()),
                ('sPassword', models.CharField(max_length=100)),
                ('sMajor', models.CharField(max_length=50)),
                ('sGrade', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.StudentInfo'),
        ),
        migrations.AddField(
            model_name='signinfo',
            name='sStudent',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='student.StudentInfo'),
        ),
        migrations.AddField(
            model_name='faceinfo',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.StudentInfo'),
        ),
    ]
